jelu:
  database:
    path: ${user.home}/.jelu/database/
  files:
    dir: '${user.home}/.jelu/files/'
  session:
    duration: 604800 #7 days
#  cors.allowed-origins:
#    - http://localhost:9000
server:
  port: 11111
spring:
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:liquibase.xml
  datasource:
    url: jdbc:sqlite:${jelu.database.path}/jelu.db?foreign_keys=on;
    username: jelu_user
    password: mypass1234
    driver-class-name: org.sqlite.JDBC
  exposed:
    generate-ddl: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-request-size: 10MB
      max-file-size: 10MB
logging:
  logback.rollingpolicy.max-history: 10
  file:
    name: ${jelu.database.path}/jelu.log
    #    name: \${user.home}/.jelu/jelu.log
  level:
    io.github.bayang.jelu: DEBUG
